
package com.guanning.web.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommonService", targetNamespace = "http://webservice.leftso.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommonService {


    /**
     * 
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "String", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservice.leftso.com/", className = "com.guanning.web.wsclient.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservice.leftso.com/", className = "com.guanning.web.wsclient.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "userName", targetNamespace = "")
        String userName);

    /**
     * 
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "String", targetNamespace = "")
    @RequestWrapper(localName = "sayCXF", targetNamespace = "http://webservice.leftso.com/", className = "com.guanning.web.wsclient.SayCXF")
    @ResponseWrapper(localName = "sayCXFResponse", targetNamespace = "http://webservice.leftso.com/", className = "com.guanning.web.wsclient.SayCXFResponse")
    public String sayCXF(
        @WebParam(name = "userName", targetNamespace = "")
        String userName);

}
